### ISSUE TITLE
SikuliRuntime command example 

### ISSUE THREAD

**Issue by stamhaney** [christianrondeau/SikuliSharp#24] opened 2018-12-13 13:41 UTC
Hello,

I would like to get the bounds (coordinates) of a control after an exists command. As this is not available directly, I used the getLastMatch in the IDE and got a successful result. However when fire the command using the SikuliRuntime, I cannot get it to work. can you help me out. Here is the function I am trying to use:

`    public void RunCommand()
    {
        using (var runtime = Sikuli.CreateRuntime(150))
        {
            runtime.Start();
            var img = Patterns.FromFile(@"F:\Shashank\tools.png", .7f);
            var result = runtime.Run(

             @"print ""RESULT:"" "+"getLastMatch() "+  "if exists(Patterns.FromFile("+"F:\\Shashank\\tools.png"+", .7f)" + ") else "+ "\"RESULT: FAIL\""   ,
              "RESULT:",
              0d
              );

        }
    }`

The pattern img, will have a different image everytime.

**Comment by christianrondeau** [comment] 2018-12-13 14:23
I'm not sure what the issue is. Maybe the Sikuli cli does not remember last matches outside of a script? I'd verify this first by launching Sikuli and typing a simple command that uses getLastMatch.

**Comment by christianrondeau** [comment] 2019-02-07 04:03
Closed by #25 (Find is now available)

**Closed by christianrondeau** 2019-02-07 04:03 UTC
